### ISSUE TITLE
Retab doesn't work on empty tab

### ISSUE THREAD

**Issue by jarradh** [bucaran/retab#2] opened 2015-04-11 12:19 UTC
I notice for some reason Retab does not seem to open on a blank tab, switching tabs with loaded page works fine.

**Comment by bucaran** [comment] 2015-04-11 12:29
I was able to reproduce this. I will fix it next week. 

Thanks for reporting this. :bow:

**Comment by jarradh** [comment] 2015-04-11 12:54
thanks for fast response and making retab! love it!

**Comment by krisdestruction** [comment] 2015-04-17 17:48
Just reproduced this today. Having the same issue!

**Comment by bucaran** [comment] 2015-04-17 23:32
@krisdestruction Thanks! Unfortunately I was too busy with work this week, but I will be working on a fix this weekend.

**Comment by bucaran** [comment] 2015-04-20 01:52
Here is my conclusion report:

+ It seems it is not possible to override Safari's default __Tab Bar Toggle__ `Cmd + Shift + Tab` when there are no tabs open.

+ It is possible to hit `Cmd+Z` to reopen the last tab anyway and then use `Cmd+Shift+Tab` as usual.

+ You can use the default `Cmd+Z` bindings and never notice this problem.

I will close the issue as `unsolved crimes`.

Thank you very much @krisdestruction and @jarradh for reporting this.

**Comment by krisdestruction** [comment] 2015-04-21 05:09
Woah wait, this issue still occurs while the page is loading. I think Safari treats that as a new tab as well but clearly there's a lag time between when it's loading and when you can `Cmd + Shift + Tab` another tab, which is annoying as hell.

**Comment by bucaran** [comment] 2015-04-21 05:12
> Woah wait, this issue still occurs while the page is loading. 

What do you mean? I

**Comment by krisdestruction** [comment] 2015-04-21 05:18
Essentially if you open 10 youtube tabs (since youtube has media, it's slow to load), close them, and reopen them by spamming `Cmd + Shift + Tab` 10 times, it doesn't all open when you press the button. The page has to partially load before the `Cmd + Shift + Tab` is responsive again.

I originally thought it was part of the same problem as I presumed that loading tabs were counted as empty tabs, but this could either be just a slow computer issue, or another issue altogether.

**Comment by bucaran** [comment] 2015-04-21 06:02
In my case it opens them and even previously closed ones (more than I need :laughing: )

Now, If you close them _all_ you won't be able to open them according to the issue described here.

Let me see if I can find anything I can do besides the hopeless `Cmd+Shift+T`.

Thanks for reopening!

**Comment by krisdestruction** [comment] 2015-04-21 06:04
Well I know it opens them properly given enough time. The issue I am experiencing is the speed at which it opens at, which is really slow. Should we fork it into another issue?

No problem at all :)

**Comment by bucaran** [comment] 2015-04-21 06:06
In my case there's a delay only in the first one, but yes, it's annoying. Yes, please open a new issue.

Thanks.

**Comment by krisdestruction** [comment] 2015-04-21 07:11
Opened as #4. I guess we can close this?

**Closed** 2015-04-21 07:14 UTC
Labels: bug, WIP
